project_id = "cchvsqeqiavhanurnbeo"

[functions.pairing-matches]
verify_jwt = false

[functions.blind-date]
verify_jwt = false

[functions.compatibility-scoring]
verify_jwt = false

[functions.swipe-action]
verify_jwt = false

[functions.subscription-management]
verify_jwt = true

[functions.profile-management]
verify_jwt = true

[functions.chat-management]
verify_jwt = false

[functions.id-verification]
verify_jwt = false

[functions.qcs-scoring]
verify_jwt = false

[functions.profile-completion]
verify_jwt = false

[functions.data-management]
verify_jwt = false

[functions.notifications-management]
verify_jwt = false

[functions.thread-management]
verify_jwt = false

[functions.chat-request-handler]
verify_jwt = false