project_id = "cchvsqeqiavhanurnbeo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

# Edge Functions
[functions.compatibility-scoring]
verify_jwt = true

[functions.swipe-action]
verify_jwt = true

[functions.pairing-matches]
verify_jwt = true

[functions.blind-date]
verify_jwt = true

[functions.subscription-management]
verify_jwt = true

[functions.profile-management]
verify_jwt = true

[functions.chat-management]
verify_jwt = true