workflows:
  build-ios:
    name: Build iOS App
    environment:
      groups:
        - apple_credentials          # 👈 use the group you created
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.flingzz.iosapp"
      node: latest
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm run build
          npx cap sync ios

      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/App.xcarchive archive \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build \
            -exportOptionsPlist ExportOptions.plist

    artifacts:
      - ios/App/build/*.ipa
      - ios/App/build/**/*.dSYM.zip
      - ios/App/build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - $APPLE_ID
