workflows:
  ios-capacitor-build:
    name: Build iOS app (FLINGZZ)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      node: latest
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/cli

      - name: Build web assets
        script: |
          npm run build || echo "No build script found"
          # Your webDir is 'dist', so ensure it's used
          npx cap copy ios

      - name: Sync Capacitor iOS project
        script: |
          npx cap sync ios

      - name: Build iOS app
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -configuration Release \
          -derivedDataPath build \
          -archivePath build/App.xcarchive \
          archive

          xcodebuild -exportArchive \
          -archivePath build/App.xcarchive \
          -exportOptionsPlist ios/App/exportOptions.plist \
          -exportPath build

    artifacts:
      - build/*.ipa
      - build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - yogeshsaini7172@gmail.com
