-- Step 1: Drop all RLS policies that depend on user_id columns
DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can manage preferences" ON partner_preferences;
DROP POLICY IF EXISTS "Users can manage their own preferences" ON partner_preferences;
DROP POLICY IF EXISTS "Users can view their own QCS" ON qcs;
DROP POLICY IF EXISTS "Users can view their own subscription limits" ON subscription_limits;
DROP POLICY IF EXISTS "Users can view their own subscription" ON subscribers;
DROP POLICY IF EXISTS "Users can view their subscription history" ON subscription_history;
DROP POLICY IF EXISTS "Users can insert their own verifications" ON identity_verifications;
DROP POLICY IF EXISTS "Users can update their own verifications" ON identity_verifications;
DROP POLICY IF EXISTS "Users can view their own verifications" ON identity_verifications;
DROP POLICY IF EXISTS "Users can manage their blocks" ON blocks;
DROP POLICY IF EXISTS "Users can create swipes" ON enhanced_swipes;
DROP POLICY IF EXISTS "Users can view their swipes" ON enhanced_swipes;
DROP POLICY IF EXISTS "Users can create matches" ON enhanced_matches;
DROP POLICY IF EXISTS "Users can update their matches" ON enhanced_matches;
DROP POLICY IF EXISTS "Users can view their matches" ON enhanced_matches;
DROP POLICY IF EXISTS "Users can create their own swipes" ON swipes;
DROP POLICY IF EXISTS "Users can view their own swipes" ON swipes;
DROP POLICY IF EXISTS "Users can create matches" ON matches;
DROP POLICY IF EXISTS "Users can view their own matches" ON matches;
DROP POLICY IF EXISTS "Users can create chat rooms" ON chat_rooms;
DROP POLICY IF EXISTS "Users can view their chat rooms" ON chat_rooms;
DROP POLICY IF EXISTS "Send messages" ON chat_messages;
DROP POLICY IF EXISTS "View own messages" ON chat_messages;
DROP POLICY IF EXISTS "Users can manage their interactions" ON user_interactions;
DROP POLICY IF EXISTS "Users can create blind date requests" ON blind_dates;
DROP POLICY IF EXISTS "Users can update blind dates they're involved in" ON blind_dates;
DROP POLICY IF EXISTS "Users can view their blind dates" ON blind_dates;
DROP POLICY IF EXISTS "Users can create reports" ON admin_reports;
DROP POLICY IF EXISTS "Users can view their own reports" ON admin_reports;
DROP POLICY IF EXISTS "Users can view their compatibility scores" ON compatibility_scores;
DROP POLICY IF EXISTS "Users can send messages" ON chat_messages_enhanced;
DROP POLICY IF EXISTS "Users can view messages in their chats" ON chat_messages_enhanced;